import React from 'react';
import './Main.css';

const Header = () => (
    <main className="main">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci dolor dolores doloribus eligendi enim eos est id illum iste iusto maxime neque obcaecati perferendis quae quasi quibusdam quod, saepe sed sint soluta tempora temporibus totam ullam ut vero vitae voluptas voluptatem? Ad doloremque dolores exercitationem incidunt possimus quibusdam reiciendis. Debitis dicta, fugiat magnam pariatur quam quo repellendus reprehenderit unde veritatis! Alias culpa dolore, dolorem dolores esse est fugit impedit magnam mollitia, nam nulla numquam odio possimus quod quos reiciendis rem repellendus sit soluta velit? Adipisci autem consectetur consequatur dicta enim excepturi, fugit id impedit incidunt nulla numquam perferendis quam quo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto culpa cum dolor doloremque ea esse exercitationem explicabo facilis harum in iusto nihil, nostrum officiis, perferendis porro quos reiciendis repellendus rerum voluptate voluptates. Aperiam at beatae eveniet facere non quae sint vero? Culpa cum, cumque dolorum ea error est harum labore laborum, magni maxime modi nam officiis perspiciatis repellat repudiandae similique tempore voluptatem? Error est et officiis possimus totam. Accusantium, aliquam aut consequatur dolorem ex facilis ipsa laboriosam magni maiores molestias nemo pariatur possimus praesentium quam, quas qui quidem reiciendis rerum sunt ullam unde voluptas voluptatibus? Ad amet beatae commodi debitis distinctio eius eveniet harum hic, incidunt nam nobis obcaecati possimus praesentium quisquam, saepe similique sint sunt. Aliquid, beatae consectetur culpa dolor dolorem doloribus dolorum earum esse in ipsum maiores mollitia natus nemo odit perspiciatis quis, quo recusandae reprehenderit suscipit velit! Deserunt dolor doloremque modi neque suscipit? Alias animi consectetur debitis dolorem, dolores fuga fugit illo minima molestiae molestias necessitatibus nihil nulla, officiis pariatur perferendis porro praesentium quam quia quidem ratione rem rerum sint sunt suscipit veritatis. Aspernatur aut beatae dolores earum facere perferendis quis suscipit temporibus, ut voluptatem. Commodi ipsam modi quod? Atque dolorum fugit nulla pariatur porro suscipit voluptate?
    </main>
);

export default Header;
